expose consturct method; customizable console.*;
robertkrimen/otto pull request #341
Opened 2019-02-25 07:56 UTC by ialex32x

2020-06-30 15:32 UTC, FabianTe commented
+1 On the abillity to supply a custom console. Considering using otto but this is still one blocker for me.

2020-12-11 05:54 UTC, andig commented
+1 for the console changes. Not sure about the construct method, that looks like a separate PR.

@ialex32x would you split this PR? @deoxxa would you consider this for merging?

2021-01-14 01:44 UTC, frankffenn commented
+1 I love this

2021-09-27 10:36 UTC, stevenh requested changes
Could you rebase this and run a go mod tidy to remove the reference to readline.

2021-09-27 10:36 UTC, stevenh commented on otto.go
> +// ialex32x: provide a method to construct js object by golang
```suggestion
// Construct provides a method to construct js object by golang.
```

2022-11-25 21:39 UTC, stevenh commented
Closing due to age with no feedback

2022-11-25 21:39 UTC, closed without merging

2022-11-25 21:52 UTC, andig commented
@stevenh there is a lot of positiv feedback. Would you want me to merge this approach into #445?