Non ascii support for some strings functions
robertkrimen/otto pull request #361
Opened 2019-10-30 15:11 UTC by arkadiont

2021-03-11 22:27 UTC, juliusrickert commented
@robertkrimen could you take a look at this? This should fix [this issue with DNScontrol](https://github.com/StackExchange/dnscontrol/issues/1092).

2021-03-11 22:34 UTC, juliusrickert commented
@deoxxa

2021-09-27 10:23 UTC, stevenh requested changes
Could you rebase to master and replace all the references to arkadiont with robertkrimen

I've detailed some example below.

2021-09-27 10:23 UTC, stevenh commented on ast/node.go
> +	"github.com/arkadiont/otto/token"
```suggestion
	"github.com/robertkrimen/otto/file"
	"github.com/robertkrimen/otto/token"
```

2021-09-27 10:23 UTC, stevenh commented on ast/walk_example_test.go
> +	"github.com/arkadiont/otto/parser"
```suggestion
	"github.com/robertkrimen/otto/ast"
	"github.com/robertkrimen/otto/file"
	"github.com/robertkrimen/otto/parser"
```

2021-09-27 10:23 UTC, stevenh commented on ast/walk_test.go
> +	"github.com/arkadiont/otto/parser"
```suggestion
	"github.com/robertkrimen/otto/ast"
	"github.com/robertkrimen/otto/file"
	"github.com/robertkrimen/otto/parser"
```

2021-09-27 10:23 UTC, stevenh commented on builtin_function.go
> +	"github.com/arkadiont/otto/parser"
```suggestion
	"github.com/robertkrimen/otto/parser"
```

2021-09-27 10:23 UTC, stevenh commented on cmpl.go
> +	"github.com/arkadiont/otto/file"
```suggestion
	"github.com/robertkrimen/otto/ast"
	"github.com/robertkrimen/otto/file"
```

2021-09-27 10:23 UTC, stevenh commented on cmpl_evaluate_expression.go
> +	"github.com/arkadiont/otto/token"
```suggestion
	"fmt"
	"github.com/robertkrimen/otto/token"
```

2021-09-27 10:23 UTC, stevenh commented on cmpl_evaluate_statement.go
> +	"github.com/arkadiont/otto/token"
```suggestion
	"fmt"
	"github.com/robertkrimen/otto/token"
```

2021-09-27 10:23 UTC, stevenh commented on cmpl_parse.go
> +	"github.com/arkadiont/otto/token"
```suggestion
	"github.com/robertkrimen/otto/ast"
	"github.com/robertkrimen/otto/file"
	"github.com/robertkrimen/otto/token"
```

2021-09-27 10:23 UTC, stevenh commented on cmpl_test.go
> +	"github.com/arkadiont/otto/parser"
```suggestion
	"github.com/robertkrimen/otto/parser"
```

2021-09-27 10:23 UTC, stevenh commented on dbg.go
> +	Dbg "github.com/arkadiont/otto/dbg"
```suggestion
	Dbg "github.com/robertkrimen/otto/dbg"
```

2021-09-27 10:23 UTC, stevenh commented on error.go
> +	"github.com/arkadiont/otto/file"
```suggestion
	"github.com/robertkrimen/otto/file"
```

2021-09-27 10:23 UTC, stevenh commented on error_native_test.go
> +		is(err1.trace[1].location(), "github.com/arkadiont/otto.TestErrorContextNative.func1.1 (error_native_test.go:15)")
```suggestion
		is(err1.trace[1].location(), "github.com/robertkrimen/otto.TestErrorContextNative.func1.1 (error_native_test.go:15)")
```

2021-09-27 10:23 UTC, stevenh commented on evaluate.go
> +	"github.com/arkadiont/otto/token"
```suggestion
	"github.com/robertkrimen/otto/token"
```

2021-09-27 10:23 UTC, stevenh commented on function_stack_test.go
> +			{native: true, nativeFile: "function_stack_test.go", nativeLine: 25, offset: 0, callee: "github.com/arkadiont/otto.TestFunction_stack.func1.1"},
```suggestion
			{native: true, nativeFile: "function_stack_test.go", nativeLine: 30, offset: 0, callee: "github.com/robertkrimen/otto.TestFunction_stack.func1.2"},
			{native: true, nativeFile: "function_stack_test.go", nativeLine: 25, offset: 0, callee: "github.com/robertkrimen/otto.TestFunction_stack.func1.1"},
```

2021-10-18 14:20 UTC, stevenh commented
Closing in favour of #423

2021-10-18 14:20 UTC, closed without merging