fieldIndexByName: Remove f.Anonymous check
robertkrimen/otto pull request #370
Opened 2020-02-03 12:03 UTC by ale-rinaldi

Fix #369 

This fixes the issue with no apparent regressions, but since I don't know why this check was in place I'm not sure that's the right solution.

2021-09-27 10:39 UTC, stevenh requested changes
Can you provide a test case which exercises this issue please.

2021-09-27 13:23 UTC, ale-rinaldi commented
Sure, I added it in `bug_test.go` as `Test_issue369`.

2021-09-27 16:22 UTC, ale-rinaldi commented
Yeah, sorry, my fault. Some time passed since I did this and I was on my first Golang works. Earlier today I was not aligned to master so I wasn't running tests correctly for some reason.

I looked at this again and my approach of totally removing the check was nonsense. I think this is OK now.

2021-09-27 20:07 UTC, stevenh requested changes
Sorry to be a pain, could you rebase to master so that we get github action tests firing please.

2021-09-28 08:26 UTC, ale-rinaldi commented
Hello, of course, I just did it 👍

2022-11-25 21:44 UTC, stevenh approved these changes

2022-11-25 21:48 UTC, merged