Preventing for(;;){} and do{}while() statements hanging forever
robertkrimen/otto pull request #374
Opened 2020-05-08 05:20 UTC by fratuz610

Hello otto maintainers :)

This is to address the for(;;){} and do{}while(true) issues that result in 100% CPU and no timeout.

The reason the code was hanging is that the timeout check happens inside `cmpl_evaluate_nodeExpression` which is never called if `len(node.body) == 0` which is precisely what happens with the empty loops above.
`while(true){}` wasn't affected because it repeatedly calls `cmpl_evaluate_nodeExpression` on the test condition of the loop already.

I know my solution is not super elegant but it's functional and addresses a real problem that is preventing a few people from putting this library in production.

2021-09-27 10:40 UTC, stevenh requested changes
Can you provide a test to confirm this works as expected please.

2021-09-29 04:06 UTC, fratuz610 commented
@stevenh there are basically little to no test cases across the whole codebase :)
The current code structure doesn't lend itself to automated testing tbh...
All I can say is that this change has been in production for over 1year at my previous company where 3rd party system integrators were creating JS snippets and have them running on our platform - all without issue

PS the irony is that I just copied the same snippet added by another maintainer in another spot

```
// Allow interpreter interruption
// If the Interrupt channel is nil, then
// we avoid runtime.Gosched() overhead (if any)
// FIXME: Test this
if self.otto.Interrupt != nil {
runtime.Gosched()
select {
case value := <-self.otto.Interrupt:
	value()
default:
}
}

```

2021-09-29 12:22 UTC, stevenh commented
> @stevenh there are basically little to no test cases across the whole codebase :) The current code structure doesn't lend itself to automated testing tbh... 

That's kind of the point in making sure we add test when making changes. It will improve the coverage and hence reliability of the package.

From your description, it should be a matter of creating test with timeout and an interrupt trigger.

2021-09-29 13:55 UTC, stevenh commented
Here's an example of something that should do the trick. Which interestingly proves that the first empty while do fix isn't needed, another reason to add tests ;-) 
```go
func TestOttoInterrupt(t *testing.T) {
        tests := []struct {
                name   string
                script string
        }{
                {
                        name:   "empty-for-loop",
                        script: "for(;;) {}",
                },
                {
                        name:   "empty-do-while",
                        script: "do{} while(true)",
                },
        }

        halt := errors.New("interrupt")
        for _, tc := range tests {
                t.Run(tc.name, func(t *testing.T) {
                        vm := New()
                        vm.Interrupt = make(chan func(), 1)
                        ec := make(chan error, 1)
                        go func() {
                                defer func() {
                                        if caught := recover(); caught != nil {
                                                if caught == halt {
                                                        fmt.Println(caught)
                                                        ec <- nil
                                                        //return
                                                }
                                                panic(caught)
                                        }
                                }()
                                _, err := vm.Run(tc.script)
                                ec <- err
                        }()

                        // Give the vm chance to execute the loop.
                        time.Sleep(time.Millisecond * 100)
                        vm.Interrupt <- func() { panic(halt) }

                        select {
                        case <-time.After(time.Second):
                                t.Fatal("timeout")
                        case err := <-ec:
                                require.NoError(t, err)
                        }
                })
        }
}
```

2022-10-07 23:13 UTC, stevenh commented
This was fixed by the linked pr

2022-10-07 23:13 UTC, closed without merging