parser/lexer: correct ID_Start & ID_Continue checks
robertkrimen/otto pull request #524
Opened 2024-06-10 13:55 UTC by filips

`unicode.IsLetter` and `unicode.IsDigit` will not return the complete set of `ID_Start` and `ID_Continue` characters defined here:  https://www.unicode.org/reports/tr31/.

2024-06-10 20:02 UTC, stevenh requested changes
Looks reasonable but lets get some tests which exercise this.

2024-06-10 23:52 UTC, filips commented
> Looks reasonable but lets get some tests which exercise this.

I added a few tests for the areas where the allowed character sets differ. Please let me know if you want me to add further tests.

2024-06-11 15:17 UTC, filips commented
@stevenh Linter warnings should be fixed now

2024-06-11 16:08 UTC, stevenh requested changes
Thanks for this, just a minor nit and then good to go.

2024-06-11 16:08 UTC, stevenh commented on parser/lexer.go
> +func UnicodeIDStart(r rune) bool {
Just a minor tweak can we unexport these:
```suggestion
func unicodeIDStart(r rune) bool {
```

2024-06-11 16:08 UTC, stevenh commented on parser/lexer.go
> +func UnicodeIDContinue(r rune) bool {
```suggestion
func unicodeIDContinue(r rune) bool {
```

2024-06-11 16:08 UTC, stevenh commented on parser/lexer.go
> +		chr >= utf8.RuneSelf && UnicodeIDStart(chr)
```suggestion
		chr >= utf8.RuneSelf && unicodeIDStart(chr)
```

2024-06-11 16:08 UTC, stevenh commented on parser/lexer.go
> +		chr >= utf8.RuneSelf && UnicodeIDContinue(chr)
```suggestion
		chr >= utf8.RuneSelf && unicodeIDContinue(chr)
```

2024-06-11 16:22 UTC, filips commented
> Thanks for this, just a minor nit and then good to go.

Sure thing, I pushed with the methods unexported

2024-06-12 09:19 UTC, stevenh approved these changes

2024-06-12 09:20 UTC, merged